### ISSUE TITLE
data parsing competition?

### ISSUE THREAD

**Issue by maelle** [ropensci/unconf16#15]
I've seen there was a competition between Hadley Wickham and Wes McKinney last year (https://github.com/ropensci/unconf/issues/17). How was it?

I wonder if it would be interesting to have a "So you think you can parse" competition, if there are good data "parsers" in the attendants? Or people that have a strong opinion about xml2 vs. XML

Exemple of terrible website with data http://www.satp.org/satporgtp/countries/india/database/indiafatalities.htm

**Comment by richfitz** [comment]
The competition ended up not happening last year; we really didn't want things to descend into language wars or a situation where people were put in a situation where they had to perform in front of a group of people.

**Comment by maelle** [comment]
ok!

**Comment by richfitz** [comment]
I think the idea of developing heuristics for parsing terrible data is a good one though!
