### ISSUE TITLE
developing heuristics for parsing terrible data

### ISSUE THREAD

**Issue by maelle** [ropensci/unconf16#16]
Exemple of terrible website with data http://www.satp.org/satporgtp/countries/india/database/indiafatalities.htm

**Comment by jennybc** [comment]
I comfort myself with snarky bingo cards in these situations.

https://github.com/jennybc/bingo#open-and-bad-data-examples

**Comment by maelle** [comment]
Well, bingo cards would be a good way to list common issues and ideas for tackling these issues. :smiley:

**Comment by maelle** [comment]
Like, how could one transform star information into a comment column. (your bingo card is so cool!)
